- name: etcd - Pause for 5 seconds so etcd can form
  ansible.builtin.pause:
    seconds: 5
    echo: no

- name: etcd - add new Nodes to Cluster
  ansible.builtin.command: "etcdctl member add {{ item }} --peer-urls=http://{{ hostvars[item].ansible_default_ipv4.address }}:2380 --endpoints={{ hostvars[existing_nodes[0]].ansible_default_ipv4.address }}:2379"
  with_items: "{{ new_nodes }}"

- name: etcd - Set Fact for config Template loop
  ansible.builtin.set_fact:
    etcd_state: existing

- name: etcd - Template etcd config
  ansible.builtin.template:
    src: etc_etcd_etcd.conf.yaml
    dest: /etc/etcd/etcd.conf.yaml
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname in new_nodes

- name: etcd - Start etcd on Bootstraped Node
  ansible.builtin.systemd_service:
    state: started
    name: etcd
  when: inventory_hostname in new_nodes
