---
- name: Basic - Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 300

- name: Basic - Add Percona Repository
  apt:
    autoremove: true
    update_cache: true
    deb: https://repo.percona.com/apt/percona-release_latest.{{ ansible_lsb.codename }}_all.deb
    state: present

- name: Basic - Enable Percona repository
  command: "percona-release setup ppg-{{ version }}"
  changed_when: true

- name: Basic - Install Postgresql on Debian
  apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  loop:
    - '{{ postgres_package }}'
  notify: Basic - clear postgresql dir

- name: etcd - Include main etcd Task
  include_tasks: etcd_main.yml

- name: patroni - Include main patroni Task
  include_tasks: patroni_main.yml
