- name: patroni - Template Patroni Config
  ansible.builtin.template:
    src: etc_patroni_patroni.yml
    dest: /etc/patroni/patroni.yml
    owner: postgres
    group: postgres
    mode: '0644'
  notify: patroni - restart patroni

- name: patroni - Deploy Patroni systemd
  ansible.builtin.copy:
    src: etc_systemd_system_patroni.service
    dest: /etc/systemd/system/patroni.service
    owner: root
    group: root
    mode: '0644'
  notify: patroni - restart patroni

- name: patroni - make sure patroni is started
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: patroni
    daemon_reload: true
